---
- name: Configurer un serveur WEB
  hosts: all
  become: true

  vars:
    packages:
      - nginx
      - curl
      - vim

  tasks:
    - name: Installer les paquets
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true

    - name: Démarrer et activer nginx
      ansible.builtin.service:
        name: nginx
        state: present
        enabled: true